package in.fissionlabs.kpinsights.service;

/**
 * <h4>Service class to perform below user services : </h4>
 * <ul>
 * <li> Verify User
 * <li> Verify PasswordResetAuthenticationToken
 * <li> Send PasswordResetMail
 * <li> Update Password
 * </ul>
 * @author bismoy
 *
 */
public interface AccessService 
{	
	/**
	 * <h4>User Verification</h4>
	 * <p>Verifies if user is valid by calling verifyUser method from AccessServiceImpl class </p>
	 * @param emailAddress email id of user used as username
	 * @returns true if user is verified otherwise false 
	 */
	Boolean verifyUser(String emailAddress);
	
	/**
	 * <h4>PasswordResetAuthenticationToken Verification</h4>
	 * <p>Verifies if password authentication token got generated by  calling authenticateToken method from authenticationService class</p>
	 * @param emailAddress email id of user used as username
	 * @param passwordResetAuthenticationToken Authentication token generated while reseting password
	 * @returns true if password authentication token gets generated successfully otherwise false
	 */
	Boolean verifyPasswordResetAuthenticationToken(String emailAddress, String passwordResetAuthenticationToken);
	
	/**
	 * <h4>Sending password reset mail </h4>
	 * <p>Sends password reset mail by calling sendPasswordResetMail method from defaultMailService class</p>
	 * @param emailAddress email id of user used as username
	 * @returns true if password reset mail is delivered otherwise false
	 */
	Boolean sendPasswordResetMail(String emailAddress);
	
	/**
	 * <h4>Update user's password</h4>
	 * <p>Updates new password by calling save method from userDAO class</p>
	 * @param username email id of user used as username
	 * @param newPassword New password of the user
	 * @returns true if user's password is updated successfully otherwise false
	 */
	Boolean updateUserPassword(String username, String newPassword);	
}
